site_name: Sublime System Verilog
site_url: https://bitbucket.org/Clams/sublimesystemverilog
pages:
- Home: 'index.md'
- User Guide:
  - 'Code Navigation' : 'navigation.md'
  - 'Completion' : 'completion.md'
  - 'Alignment' : 'alignment.md'
  - 'Module Instance' : 'instance.md'
  - 'Keybinding' : 'keybind.md'
theme: readthedocs